language: ruby
rvm:
 - 2.5.0

services:
  - mysql

test:
 adapter: mysql2
 database: tutoria_test
 username: travis
 encoding: utf8

before_install:
 - gem install bundler -v "$(grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -n 1)"
 - mysql -e 'CREATE DATABASE tutoria_test;'

script:
 - RAILS_ENV=test bundle exec rake db:migrate --trace
 - bundle exec rake db:test:prepare
 - bundle exec rake db:seed
 - bundle exec rspec
